### ISSUE TITLE
npm install node-gyp error

### ISSUE THREAD

**Issue by ChristianTaidi** [alastria/alastria-identity-entity#17]
### I´m using:
- Ubuntu 18.04.4 LTS OS 
- node v12.16.1
- node-gyp v5.0.5
- npm v6.13.4

**Comment by DaniRumpi** [comment]
Hi @ChristianTaidi , have you tried to use **node v10.15**? The software is not prepared to use version 12.X.

**Comment by ChristianTaidi** [comment]
That might be the problem, thank you very much
